# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employees.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='employees.proto',
  package='default',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x65mployees.proto\x12\x07\x64\x65\x66\x61ult\"J\n\x08\x45mployee\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x66_name\x18\x02 \x01(\t\x12\x0e\n\x06l_name\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x02\"1\n\tEmployees\x12$\n\temployees\x18\x01 \x03(\x0b\x32\x11.default.Employeeb\x06proto3'
)




_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='default.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emp_id', full_name='default.Employee.emp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f_name', full_name='default.Employee.f_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l_name', full_name='default.Employee.l_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salary', full_name='default.Employee.salary', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=102,
)


_EMPLOYEES = _descriptor.Descriptor(
  name='Employees',
  full_name='default.Employees',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='employees', full_name='default.Employees.employees', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=153,
)

_EMPLOYEES.fields_by_name['employees'].message_type = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Employees'] = _EMPLOYEES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEE,
  '__module__' : 'employees_pb2'
  # @@protoc_insertion_point(class_scope:default.Employee)
  })
_sym_db.RegisterMessage(Employee)

Employees = _reflection.GeneratedProtocolMessageType('Employees', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEES,
  '__module__' : 'employees_pb2'
  # @@protoc_insertion_point(class_scope:default.Employees)
  })
_sym_db.RegisterMessage(Employees)


# @@protoc_insertion_point(module_scope)
